# Generated by Django 3.1.5 on 2021-02-13 20:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_title', models.CharField(max_length=255, verbose_name='Navn')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Telefonnummer')),
                ('email_address', models.CharField(max_length=255, verbose_name='Email adresse')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='Åbningstider')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255, verbose_name='betegnelse')),
                ('description', ckeditor.fields.RichTextField(verbose_name='beskrivelse')),
                ('photo', models.ImageField(upload_to='photos/%Y/%M/%D')),
                ('facebook_link', models.URLField(max_length=255)),
                ('twitter_link', models.URLField(max_length=255)),
                ('instagram_link', models.URLField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_aboutPage', models.BooleanField(default=False, verbose_name='er på (about sida)')),
            ],
        ),
    ]
