# Generated by Django 3.1.5 on 2021-02-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='email_address',
            field=models.CharField(max_length=255, verbose_name='Email adresse'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='name_title',
            field=models.CharField(max_length=255, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='opening_hours',
            field=models.CharField(max_length=255, verbose_name='Åbningstider'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Telefonnummer'),
        ),
    ]
