# Generated by Django 3.1.5 on 2021-02-06 21:28

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980)], verbose_name='year')),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reduced_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Bakkamera', 'Bakkamera'), ('Fartpilot, manuel', 'Fartpilot, manuel'), ('Fartpilot, adaptiv', 'Fartpilot, adaptiv'), ('Fjernlys assistent', 'Fjernlys assistent'), ('Kurvelys', 'Kurvelys'), ('Vognbaneassistent', 'Vognbaneassistent'), ('Alufælge', 'Alufælge'), ('Anhængertræk, fast', 'Anhængertræk, fast'), ('Anhængertræk, aftageligt', 'Anhængertræk, aftageligt'), ('LED forlygter', 'LED forlygter'), ('Soltag, manuelt', 'Soltag, manuelt'), ('Soltag, elektrisk', 'Soltag, elektrisk'), ('Panoramatag', 'Panoramatag'), ('Xenonlygter', 'Xenonlygter'), ('Android auto', 'Android auto'), ('Apple carplay', 'Apple carplay'), ('Elruder', 'Elruder'), ('Gear, manuel', 'Gear, manuel'), ('Headup display', 'Headup display'), ('Navigation', 'Navigation'), ('Nøglefri betjening', 'Nøglefri betjening'), ('Varme i sæder', 'Varme i sæder'), ('Varme, aircondition', 'Varme, aircondition'), ('Varme, klimaanlæg', 'Varme, klimaanlæg')], max_length=362)),
                ('body_style', models.CharField(max_length=100)),
                ('transmission', models.CharField(choices=[('Automatisk ', 'Automatisk'), ('Manuel', 'Manuel')], max_length=25)),
                ('km', models.IntegerField()),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('Bensin', 'Bensin'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('EL', 'EL'), ('Ethanol', 'Ethanol')], max_length=10)),
                ('no_of_owners', models.CharField(blank=True, max_length=100, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
