# Generated by Django 3.1.5 on 2021-02-06 21:48

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='no_of_owners',
        ),
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(max_length=100, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(max_length=100, verbose_name='bil kaross stil'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=255, verbose_name='Biltitel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=100, verbose_name='farve'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tilstand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, verbose_name='døre'),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bakkamera', 'Bakkamera'), ('Fartpilot, manuel', 'Fartpilot, manuel'), ('Fartpilot, adaptiv', 'Fartpilot, adaptiv'), ('Fjernlys assistent', 'Fjernlys assistent'), ('Kurvelys', 'Kurvelys'), ('Vognbaneassistent', 'Vognbaneassistent'), ('Alufælge', 'Alufælge'), ('Anhængertræk, fast', 'Anhængertræk, fast'), ('Anhængertræk, aftageligt', 'Anhængertræk, aftageligt'), ('LED forlygter', 'LED forlygter'), ('Soltag, manuelt', 'Soltag, manuelt'), ('Soltag, elektrisk', 'Soltag, elektrisk'), ('Panoramatag', 'Panoramatag'), ('Xenonlygter', 'Xenonlygter'), ('Android auto', 'Android auto'), ('Apple carplay', 'Apple carplay'), ('Elruder', 'Elruder'), ('Gear, manuel', 'Gear, manuel'), ('Headup display', 'Headup display'), ('Navigation', 'Navigation'), ('Nøglefri betjening', 'Nøglefri betjening'), ('Varme i sæder', 'Varme i sæder'), ('Varme, aircondition', 'Varme, aircondition'), ('Varme, klimaanlæg', 'Varme, klimaanlæg')], max_length=362, verbose_name='funktioner'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Bensin', 'Bensin'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('EL', 'EL'), ('Ethanol', 'Ethanol')], max_length=10, verbose_name='brændstoftype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='bilmærke'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pris'),
        ),
        migrations.AlterField(
            model_name='car',
            name='reduced_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nedsat pris'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatisk ', 'Automatisk'), ('Manuel', 'Manuel')], max_length=25, verbose_name='gear'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980)], verbose_name='år'),
        ),
    ]
