# Generated by Django 3.1.5 on 2021-02-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210209_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='model_name',
        ),
    ]
