# Generated by Django 3.1.5 on 2021-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20210223_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reduced_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='nedsat pris'),
        ),
    ]
