# Generated by Django 3.1.5 on 2021-02-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210223_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='er nyhed'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Solgt'),
        ),
    ]
